#!/bin/sh
#
# @name COEX Clover SITL (with Vision Position Estimation)
#
# @type Quadrotor Wide
#

sh /etc/init.d-posix/4500_clover

if [ $AUTOCNF = yes ]
then
	# EKF2
	param set EKF2_AID_MASK 26
	param set EKF2_EVP_NOISE 0.1
	param set EKF2_EVA_NOISE 0.1
	param set EKF2_EV_DELAY 0
	param set EKF2_OF_DELAY 0
	param set EKF2_OF_QMIN 10
	param set EKF2_OF_N_MIN 0.05
	param set EKF2_OF_N_MAX 0.2

	# LPE
	param set LPE_FUSION 118
	param set ATT_W_EXT_HDG 0.5
	param set LPE_VIS_XY 0.1
	param set LPE_VIS_Z 0.1
	param set LPE_VIS_DELAY 0

fi
